site_name: Carbon FAQ's

site_url: "https://gadgetplus.pt/Carbon-FAQS/"
site_autor: "Edgar Mata"
site_description: "Centro de conhecimento Gadget Plus.LDA"

copyright: |
  &copy; 2024 <a href="https://gadgetplus.pt/" target="_blank" rel="noopener">Gadget Plus, LDA</a>

repo_name: "CarbonFAQS"
repo_url: "https://github.com/GadgetPlusKDB/Carbon-FAQS"

theme:
  logo: assets/logo.svg
  favicon: images/favicon.png
  name: material
  features:
    - navigation.tabs
#   - navigation.sections
    - navigation.path
    - navigation.expand
    - navigation.footer 
    - toc.follow  
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy        
  languare: pt
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Preferencias de sistema

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Mudar para modo escuro
      primary: indigo
      accent: blue

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Mudar para modo Claro
      primary: indigo
      accent: blue

  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: material/lightbulb-on-10
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16     

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/EdgarMata
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/profile.php?id=61550788541239
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/gadgetplusoficial/
    - icon: fontawesome/solid/paper-plane
      link: mailto:contacto@gadgetplus.pt
  analytics:
    provider: google
    property: G-9TXDKKF1D6
    feedback:
      title: Esta pagina ajudou?
      ratings:
        - icon: material/thumb-up-outline
          name: Esta pagina ajudou
          data: 1
          note: >-
            Obrigado pelo feedback!
        - icon: material/thumb-down-outline
          name: Esta pagina pode melhorar
          data: 0
          note: >- 
            Obrigado pelo feedback! Ajuda-nos a melhorar esta pagina
            usando o nosso <a href="https://docs.google.com/forms/d/e/1FAIpQLSf_kuzfD_Tbez4b-jqxr0dPAsu4QGP72imTuG0AKUAi-gQKLg/viewform?usp=pp_url&entry.756152555={url}" target="_blank" rel="noopener">formulario de feedback</a>.     
#  alternate:
#    - name: Português
#    - link: /pt/
#    - lang: pt
#    - name: Espanhol
#    - link: /es/
#    - lang: es
#    - name: Françês
#    - link: /fr/
#    - name
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.caret
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.keys
  - toc:
      permalink: true
      title: Tabela de Conteudo

nav:
  - Home: index.md
  - Manual:
    - manual/index.md    
    - Primeiros Passos:
      - Instalar Carbon: manual/primeiros-passos/instalar-carbon.md
      - Instalar Software: manual/primeiros-passos/instalar-software.md
      - Conexão: manual/primeiros-passos/conexão-computador.md
      - Encher Reservatório: manual/primeiros-passos/encher-reservatório.md
      - Remover Suportes: manual/primeiros-passos/remover-suportes.md
      - Colmeia: manual/primeiros-passos/colmeia.md
    # - Eixo Rotativo: manual/primeiros-passos/eixo-rotativo.md
    - Primeiros Trabalhos:
      - Ajustar Foco: manual/primeiros-trabalhos/ajustar-foco.md
      - Materiais: manual/primeiros-trabalhos/material.md
      - Velocidade e Potencia: manual/primeiros-trabalhos/velocidade-potencia.md
      - Tesoura Pincel Impressora: manual/primeiros-trabalhos/tesoura-impressora.md
      - Primeiro Corte: manual/primeiros-trabalhos/primeiro-corte.md
      - Primeira Gravação: manual/primeiros-trabalhos/primeira-gravação.md
  - Manutenção: 
    - Água:
      - Água na Carbon: manutenção/água/agua-na-carbon.md
      - Trocar Água: manutenção/água/trocar-agua.md
      - Tenho Bolhas: manutenção/água/tenho-bolhas.md
    - Limpeza:
      - Frequencia da limpeza: manutenção/limpeza/frequencia-limpeza.md
      - Limpeza dos espelhos: manutenção/limpeza/limpeza-espelhos.md
      - Limpeza do Exaustor: manutenção/limpeza/limpeza-exaustor.md
      - Limpeza do Interior: manutenção/limpeza/limpeza-interior.md
      - Limpeza da lente: manutenção/limpeza/limpeza-lente.md
      - Limpeza da lendo do tubo: manutenção/limpeza/limpeza-lente-tubo.md
  - Segurança:
    - Instruções de Segurança: segurança/instrucões-seguranca.md
    - Instruções de Tomadas: segurança/aterramento-tomadas.md
    - Cuidados com Materiais: 
      - Corte ABS: segurança/cuidados-materiais/corte-ABS.md
      - Corte PVC: segurança/cuidados-materiais/corte-PVC.md
  - Studio:
    - Primeiros Passos:
      - Janela Inicial: studio/primeiros-passos/janela-inicial.md
      - Camadas: studio/primeiros-passos/camadas.md
      - Comandos Conexão: studio/primeiros-passos/comando-conexão.md
      - Comandos Movimento: studio/primeiros-passos/comando-movimento.md
      - Função Preview: studio/primeiros-passos/função-preview.md
      - Icons Simbólicos: studio/primeiros-passos/icons-simbólicos.md
      - Como utilizar Camera 4K: studio/primeiros-passos/utilizar-camera.md
    - Tutorial Basico:
      - Principios Basicos: studio/tutorial-basico/principios-basicos.md
      - Formas: studio/tutorial-basico/formas.md
    - Tutorial Intermedio:
      - Vetorização: studio/tutorial-intermedio/vetorização.md
      - Vetorizar Pixeis: studio/tutorial-intermedio/vetorizar-pixeis.md
    - Tutorial Avançado:
      - Desenho Livre: studio/tutorial-avançado/desenho-livre.md
      - Caligrafia: studio/tutorial-avançado/caligrafia.md
      - Interpolação: studio/tutorial-avançado/interpolação.md
    - Conexão Camera 4K: studio/camera-4k.md
    - Atualização Software: studio/altualização-software.md
    - Truques & Dicas: studio/truques-&-dicas.md      
  - Troubleshooting:
    - Corte Diferente:
      - Ajustar Correias: troubleshooting/corte-diferente/ajustar-correias.md
      - Desenho Errado: troubleshooting/corte-diferente/desenho-errado.md
      - Ajustar Foco: troubleshooting/corte-diferente/ajustar-foco.md      
    - Não Corta:
      - Como Funciona o tubo: troubleshooting/não-corta/como-funciona-tubo.md
      - Não corta o material: troubleshooting/não-corta/não-corta.md
      - Não Sai Laser: troubleshooting/não-corta/não-sai-laser.md
      - Laser Fraco: troubleshooting/não-corta/laser-fraco.md
      - Verificar Espelhos: troubleshooting/não-corta/verificar-espelhos.md
      - Alinhar Espelhos: troubleshooting/não-corta/alinhar-espelhos.md
      - Fogo no Corte: troubleshooting/não-corta/fogo-no-corte.md
    - Não Conecta:
      - Cabo USB: troubleshooting/não-conecta/cabo-usb.md
      - Cartão SD: troubleshooting/não-conecta/cartão-sd.md
      - Wi-Fi Carbon: troubleshooting/não-conecta/wifi-carbon.md
      - Wi-Fi Rede Local: troubleshooting/não-conecta/wifi-local.md
      - Verificar Placa: troubleshooting/não-conecta/verificar-placa.md
    - Sensores:
      - Sensor de nivel água: troubleshooting/sensores/sensor-nivel-agua.md
      - Sensor de porta: troubleshooting/sensores/sensor-porta.md
      - Sensor de Temperatura: troubleshooting/sensores/sensor-temperatura.md
    - Software:
      - Barra não Abre: troubleshooting/software/barra-não-abre.md
      - Sem Preview: troubleshooting/software/sem-preview.md
      - Imagem da Camera Preta: troubleshooting/software/camera-mostra-preto.md
  - Downloads:
    - transferencias/index.md
  - Truques & Dicas: 
    - Vetorizar Imagens: truques-&-dicas/vetorizar-imagem.md
    - Gravar fotografias: truques-&-dicas/gravar-fotos.md
    - Importar: truques-&-dicas/importar.md
    - Exportar Silhouette: truques-&-dicas/exportar-silhouette.md
    - Teste de Parâmetros: truques-&-dicas/testes-parametros.md
    - Influencia da velocidade e potencia: truques-&-dicas/influ-velocidade-material.md
    - Tabela de parâmetros: truques-&-dicas/tabela-parametros.md
    - Boas práticas: truques-&-dicas/boas-praticas.md
    - Dicas para contorno: truques-&-dicas/dicas-controno.md
    - Dicas para gravação: truques-&-dicas/gravacao-perfeita.md
    - Cortando material impresso: truques-&-dicas/material-impresso.md
    - Orimizar tempos: truques-&-dicas/otimizar-tempo.md
    - Orçamentação: truques-&-dicas/orcamentacao.md
    - Cortar MDF: truques-&-dicas/cortar-mdf.md
    - Fazer carimbos: truques-&-dicas/fazer-carimbos.md
    - Gravação em metal: truques-&-dicas/gravacao-metal.md
    - Reduzir acabamento queimado: truques-&-dicas/acabamento-queimado.md
    - Linhas tracejadas: truques-&-dicas/linhas-tracejadas.md
    - Fazer um letreiro: truques-&-dicas/fazer-letreiro.md
    - Acrílicos espelhados: truques-&-dicas/acrilico-espelhado.md
    - Codigos Spotify: truques-&-dicas/spotify-code.md
